In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
list1 = [1, 2, 3, 4]

In [4]:
array1 = np.array(list1)
print(array1)

[1 2 3 4]


In [5]:
list2 = [[1,2,3], [4,5,6]]
array2 = np.array(list2)
print(array2)

[[1 2 3]
 [4 5 6]]


In [6]:
toyPrices = np.array([5,8,3,6])
print(toyPrices - 2)

[3 6 1 4]


In [7]:
# if you wanted to do this manually...

In [10]:
toyPrices = [5,8,3,6]

In [11]:
for i in range(len(toyPrices)):
    toyPrices[i] -=2
print(toyPrices)

[3, 6, 1, 4]


In [21]:
dataf = pd.DataFrame([
    ['John Smith','123 Main St',34],
    ['Jane Doe', '456 Maple Ave',28],
    ['Joe Schmo', '789 Broadway',51]
    ],
    columns=['name','address','age'])
print(dataf)

         name        address  age
0  John Smith    123 Main St   34
1    Jane Doe  456 Maple Ave   28
2   Joe Schmo   789 Broadway   51


In [22]:
dataf.set_index('name')
print(dataf)

         name        address  age
0  John Smith    123 Main St   34
1    Jane Doe  456 Maple Ave   28
2   Joe Schmo   789 Broadway   51
